### ISSUE TITLE
Not a issue just a Request.

### ISSUE THREAD

**Issue by Exraiel** [TheMaverickProgrammer/battlenetwork#9]
Lobby Homepage Builder, The Ability to place Networld squares & decor to interact with & invite others into that space, along with this a chat email sent/delete ability to other players+Net Battle.

This is a bit advanced but hoping this is where this project heads.

Being able to have the Networld to explore/customize & summon/fight viruses/navis is a very important step forward if even possible, I'd no understanding how one would do it although.

Next Would be adding the Navi Customizer Programs while able to make your own & name them.

Style/Cross Form Selection is another big one bigger able to transfrom mid-battle or Network & could look at stats/abilities in the Navi Screen much like how Chrono X Does with theirs currently.
Create & Share up to 6 Forms & Load them to your opponent during the match so they can see the forms during battles, this would lead to some crazy battles, as each Form will change out their Navi Customizer Programs thus changing something as simple as Megamans Color & Element Atk, to using a shield or sword/other weapon. 

Lastly Place your chips in a trader to have them sell at a price of your choosing & let other players buy them, Same Win HP/MB ITEMS AS SUBCHIPS & Sell them too alongside Navi Custom Programs.

You can make Navi Programs like snap ons, a +50hp snaps to another +50hp of the same color to become a 2 square +100hp. same for Atk/SPD/Charge Chip+ thus building these amazing programs that are semi fused into better versions.

All these addons will build this game into a version worthy to Call a MMORPG & Game shared by all, Create your own Net Areas to link to others players have made for a true WWNET Experience.

**Comment by TheMaverickProgrammer** [comment]
Adding more battle content is my next priority. This means more enemies, more chips, more bosses. And chips will be scripted this time. That's another feature I'm adding next. This should make it easier to add more content.

Overworld itself has already been requested and it is beyond the scope of this project. This engine is focusing on the battle mechanics only. There has been talk about PvP and lobbys for battling but will come only after more content is added and everything is working as expected.

Navi cust won't be added because, with scripting, programmers can just code new navis with features and release mods.

Forms have also been requested but with the ability to choose an infinite number of custom navis from the navi menu makes this redundant. It also won't make sense to code because each beast out/style crosses are for megaman only. 

Chips are classified as mods too. People can just download and play with new chips by dragging and dropping a folder with the mod info.

At this time I'm not interested in making an MMORPG. I'm focused on making the battle engine as robust as possible with enough content to be fun and easy to mod.

**Comment by Exraiel** [comment]
Thx, this is open sourced correct, does that mean anyone is free add onto their own version of this as they choose to able to lan/host & connect to whom ever, all I'm suggesting was a place to host a collection of addons not intended for your end product but rather a modding format so others can patch together their own MMBN Worlds, I'm just looking for those willing to offer the time to create these tool patches thus creating their own works & share them between each other ingame hacked/modded or not, I can clearly see you've put a lot of work into this & learning the base construct for my own version is my goal, I'll likely be creating a Hub myself to host/share these patch tools online, I just need a starting point, a battle emulator is a tool which can be downloaded from a source like you & if you don't mind sharing a link to a hub site of mine later for that I'd would be very thankful.

Hopefully I can find someone willing to create open source tools to achieve my ideal Networld MMBN.
Really thats all one can hope for smart programmers who see potential ones own concept vision for it.

**Comment by TheMaverickProgrammer** [comment]
Yes you can take and use the source code. Feel free to fork and use as you'd like as long as you credit me. If you want to add overworld that would be really cool.

**Comment by Exraiel** [comment]
https://www.patreon.com/exraiel_creations
I've been create sprites which could be used,

**Comment by TheMaverickProgrammer** [comment]
Hello, join the official Discord to advertise. Maybe players and makers can
use your talents!

https://discordapp.com/invite/ZwCqYNZ
